c_compiler: gcc
c_compiler_version: '7'
cxx_compiler: gxx
cxx_compiler_version: '7'
extend_keys:
  - extend_keys
  - pin_run_as_build
  - ignore_build_only_deps
  - ignore_version
fortran_compiler: gfortran
ignore_build_only_deps:
  - numpy
  - python