{% set name = "sofa-cmake" %}

package:
  name: "{{ name }}"
  version: {{ environ.get('NEW_GIT_TAG', 'dev') }}

source:
  git_url: ../

requirements:
    build:
        - cmake
        - {{ compiler('c') }}              # [not win]
#        - m2w64-gcc                        # [win]
        - vs2017_{{ target_platform  }}    # [win]

about:
  home: https://github.com/ggarrett13/sofa
  license: BSD
  license_family: BSD
  summary: Standards of Fundamental Astronomy code, copyright of the Board of the International Astronomical Union.
